#:schema node_modules/wrangler/config-schema.json
name = "sistema-equipamentos-medicos"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "equipamentos_medicos_db"
database_id = "local"
